Description: PyPSA - DispaSET Unleash Sector Power
SimulationType: Integer clustering
SimulationDirectory: Simulations/PyPSA_ DispaSET_Unleash/Reff/SectPower_2030
StartDate: !!python/tuple
- 2030
- 1
- 1
- 0
- 0
- 0
StopDate: !!python/tuple
- 2030
- 1
- 31
- 0
- 0
- 0
DataTimeStep: 1
SimulationTimeStep: 1
HorizonLength: 4
LookAhead: 1
AllowCurtailment: 1
GAMS_folder: ''
Demand: Database_PyPSA/Reference_Scenario/Load_RealTime/##/1h/2030.csv
RenewablesAF: Database_PyPSA/Reference_Scenario/AvailabilityFactors/##/1h/2030.csv
Outages: ''
ShareOfFlexibleDemand: ''
DemandFlexibility: ''
LoadShedding: ''
PowerPlantData: Database_PyPSA/Reference_Scenario/PowerPlants/##/2030.csv
NTC: Database_PyPSA/Reference_Scenario/NTC/1h/2030.csv
Interconnections: Database_PyPSA/Reference_Scenario/CrossBorderFlows/1h/2030.csv
TransmissionGridType: NTC
GridData: ''
GeoData: ''
HydroScheduling: 'Off'
HydroSchedulingHorizon: Annual
InitialFinalReservoirLevel: 1
ReservoirLevels: Database_PyPSA/Reference_Scenario/HydroData/ReservoirLevel/##/1h/2030.csv
ReservoirLevelInitial: ''
ReservoirLevelFinal: ''
ReservoirScaledInflows: Database_PyPSA/Reference_Scenario/HydroData/ScaledInflows/##/1h/2030.csv
StorageAlertLevels: ''
StorageFloodControl: ''
WaterValue: ''
CostLoadShedding: ''
CostCurtailment: ''
CostOfSpillage: ''
CostXNotServed: ''
ValueOfLostLoad: ''
PriceTransmission: ''
PriceOfGas: ''
PriceOfBlackCoal: ''
PriceOfLignite: ''
PriceOfCO2: ''
PriceOfBiomass: ''
PriceOfFuelOil: ''
PriceOfNuclear: ''
PriceOfPeat: ''
PriceOfAmmonia: ''
ReserveCalculation: Generic
ShareOfQuickStartUnits: ''
Reserve2U: ''
Reserve2D: ''
PrimaryReserveLimit: ''
InertiaLimit: ''
FFRLimit: ''
FFRGainLimit: ''
FrequencyStability: 'Off'
SystemGainLimit: ''
BoundarySectorData: ''
BoundarySectorNTC: ''
BoundarySectorInterconnections: ''
SectorXDemand: ''
SectorXFlexibleDemand: ''
SectorXFlexibleSupply: ''
SectorXReservoirLevels: ''
SectorXFloodControl: ''
BoundarySectorMaxSpillage: ''
OptimalityGap: 0.0015
modifiers:
  Demand: 1
  Solar: 1
  Wind: 1
  Storage: 1
zones:
- BE
- DE
- FR
- NL
all_zones:
- BE
- DE
- FR
- NL
ReserveParticipation:
- COMC
- GTUR
- HDAM
- HPHS
- ICEN
- CAES
- BATS
- BEVS
- P2HT
ReserveParticipation_CHP: []
default:
  ShareOfFlexibleDemand: 0
  DemandFlexibility: 4
  LoadShedding: 0.05
  ReservoirLevelInitial: 0.5
  ReservoirLevelFinal: 0.5
  WaterValue: 400
  CostLoadShedding: 1500
  CostCurtailment: 0
  CostOfSpillage: 4
  ValueOfLostLoad: 100000
  PriceTransmission: 0
  PriceOfGas: 44
  PriceOfBlackCoal: 18
  PriceOfLignite: 15
  PriceOfCO2: 88.55
  PriceOfBiomass: 33
  PriceOfFuelOil: 61
  PriceOfNuclear: 4
  PriceOfPeat: 33
  PriceOfAmmonia: 76
  ShareOfQuickStartUnits: 0.5
  PrimaryReserveLimit: 0
  InertiaLimit: 0
  FFRLimit: ''
  FFRGainLimit: ''
  SystemGainLimit: 0
